CREATE DATABASE flowshop;
USE flowshop;

CREATE TABLE produk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    harga INT NOT NULL,
    foto VARCHAR(255) NOT NULL
);